apiVersion: 1
groups:
    - orgId: 1
      name: Alarms
      folder: Alarms
      interval: 10m
      rules:
        - uid: qnViO7zRz
          title: Nibe tuloilma
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: _2YhzQigk
              model:
                groupBy:
                    - params:
                        - $__interval
                      type: time
                    - params:
                        - none
                      type: fill
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                measurement: Nibe
                orderByTime: ASC
                policy: default
                refId: A
                resultFormat: logs
                select:
                    - - params:
                            - value
                        type: field
                      - params: []
                        type: last
                tags:
                    - key: sensor
                      operator: =
                      value: BT22 Supply air temp
            - refId: B
              datasourceUid: "-100"
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: mean
                refId: B
                settings:
                    mode: ""
                type: reduce
            - refId: C
              datasourceUid: "-100"
              model:
                conditions:
                    - evaluator:
                        params:
                            - 20
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: min
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $B < 13
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: math
          noDataState: NoData
          execErrState: Alerting
          for: 30m
          isPaused: false
