{
 "title": "Koti",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Lämpötilat",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lämpötila sauna",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Sauna" }
     ]
    }
   ]
  },
  {
   "title": "Lämpötila sauna",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Sauna" }
     ]
    }
   ]
  },
  {
   "title": "Kosteus",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lämpötila ulkona",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Ulkona" }
     ]
    }
   ]
  },
  {
   "title": "Lämpötila terassi",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Terassi" }
     ]
    }
   ]
  },
  {
   "title": "Lämpötila jääkaappi",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Jaakaappi" }
     ]
    }
   ]
  },
  {
   "title": "Lämpötila olohuone",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Olohuone" }
     ]
    }
   ]
  },
  {
   "title": "Lämpötila makkari",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Makkari" }
     ]
    }
   ]
  },
  {
   "title": "Lämpötila varasto",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Varasto" }
     ]
    }
   ]
  },
  {
   "title": "Tunnistimet",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_deviceName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "contact",
     "query": "SELECT last(\"valueBinary\") FROM \"contact\" WHERE (\"deviceName\" = 'Takaovi') AND $timeFilter GROUP BY time($__interval), \"deviceName\"",
     "select": [
      [
       { "params": [ "valueBinary" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}