{
 "title": "Mitsu",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Olohuone",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"deviceName\" = 'Olohuone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Olohuone" }
     ]
    },
    {
     "alias": "Ulkona",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"deviceName\" = 'Ulkona')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Ulkona" }
     ]
    },
    {
     "alias": "RoomTemperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mcloud",
     "select": [
      [
       { "params": [ "RoomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DeviceName", "operator": "=", "value": "Mitsu" }
     ]
    },
    {
     "alias": "SetTemperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mcloud",
     "select": [
      [
       { "params": [ "SetTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "DeviceName", "operator": "=", "value": "Mitsu" }
     ]
    }
   ]
  },
  {
   "title": "CurrentEnergyConsumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "CurrentEnergyConsumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DeviceName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mcloud",
     "query": "SELECT \"CurrentEnergyConsumed\" FROM \"mcloud\" WHERE (\"DeviceName\" = 'Mitsu')",
     "select": [
      [
       { "params": [ "CurrentEnergyConsumed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DeviceName", "operator": "=", "value": "Mitsu" }
     ]
    }
   ]
  },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "alias": "ActualFanSpeed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mcloud",
     "select": [
      [
       { "params": [ "ActualFanSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DeviceName", "operator": "=", "value": "Mitsu" }
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mcloud",
     "query": "SELECT (spread(\"CurrentEnergyConsumed\") / 1000 ) FROM \"mcloud\" WHERE (\"DeviceName\" = 'Mitsu') AND $timeFilter",
     "select": [
      [
       { "params": [ "CurrentEnergyConsumed" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ],
     "tags": [
      { "key": "DeviceName", "operator": "=", "value": "Mitsu" }
     ]
    }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mcloud",
     "select": [
      [
       { "params": [ "OperationMode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DeviceName", "operator": "=", "value": "Mitsu" }
     ]
    }
   ]
  }
 ]
}