{
 "title": "Nibe",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Air temps",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Nibe",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "BT20 exhaust air temp" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "BT21 vented air temp" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "BT22 Supply air temp" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "BT16 Evaporator temp" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "BT1 Outdoor temperature" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "Compressor blocked" }
     ]
    }
   ]
  },
  {
   "title": "Internal electrical addition power / hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Nibe",
     "query": "SELECT sum(\"mean\")/3600 FROM ( SELECT mean(\"value\") FROM \"Nibe\" WHERE sensor='Internal electrical addition power' AND $timeFilter GROUP BY time(1s) fill(previous) ) WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "Internal electrical addition power"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal electrical addition power / total / timerange",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Nibe",
     "query": "SELECT sum(\"mean\")/3600 FROM ( SELECT mean(\"value\") FROM \"Nibe\" WHERE sensor='Internal electrical addition power' AND $timeFilter GROUP BY time(1s) fill(previous) ) WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "Internal electrical addition power"
      }
     ]
    }
   ]
  },
  {
   "title": "Compressor blocked",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Nibe",
     "query": "SELECT count(\"value\") FROM \"Nibe\" WHERE (\"sensor\" = 'Compressor blocked' AND \"value\" = 20) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Compressor blocked" }
     ]
    }
   ]
  },
  {
   "title": " Underfloor heating",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Nibe",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "BT1 Outdoor temperature" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "Floor water in" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "Floor water out" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "Calc floor water supply" }
     ]
    },
    {
     "alias": "Living room temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=", "value": "Olohuone" }
     ]
    }
   ]
  },
  {
   "title": "Hot water",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Nibe",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Water load" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "Water top" }
     ]
    }
   ]
  }
 ]
}